### ISSUE TITLE
Density option is broken.

### ISSUE THREAD

**Issue by Zirafnik** [yakovmeister/pdf2image#162] opened 2023-04-18 23:19 UTC
Density option has no effect on the final result.

I have flied through the library code and at first glance it seems that the problem is not on 'pdf2pic' end, as all the `gm` calls seem to be okay. 

But none of the dependencies upstream report this issue. Not the node `gm` library we are using, and not the GraphicsMagick itself.

It would be great if somebody could test the `gm` dependency alone, and see if the problem is coming from there. If `density` works in `gm`, then the problem lies here.

**Comment by Zirafnik** [comment] 2023-04-19 00:24
I tested this quickly, and it appears that the 'gm' library upstream is broken somehow, as even directly passing in higher density values, nothing changed.

**Comment by mskec** [comment] 2023-05-11 22:27
Hi @Zirafnik,

I tested different density options and I can see difference in the output. 
Here is my test file https://github.com/mskec/pdf2image/commit/161e7c834c4627f0e3372d57b7a414e5a8d5ed04
I have `gm@1.23.1`.

**Comment by mskec** [comment] 2023-06-17 14:06
I'll close the issue. Feel free to submit more info if you think the problem is in pdf2pic.

**Closed by mskec** 2023-06-17 14:06 UTC
