### ISSUE TITLE
problem canvas

### ISSUE THREAD

**Issue by woxman** [yakovmeister/pdf2image#171] opened 2023-06-16 13:42 UTC
i see this problem

`node:internal/modules/cjs/loader:1280
return process.dlopen(module, path.toNamespacedPath(filename));
^

Error: The specified procedure could not be found.
\?\D:\azarakhsh\node_modules\canvas\build\Release\canvas.node
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1280:18)
at Module.load (node:internal/modules/cjs/loader:1074:32)
at Function.Module._load (node:internal/modules/cjs/loader:909:12)
at Module.require (node:internal/modules/cjs/loader:1098:19)
at require (node:internal/modules/cjs/helpers:108:18)
at Object. (D:\azarakhsh\node_modules\canvas\lib\bindings.js:3:18)
at Module._compile (node:internal/modules/cjs/loader:1196:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
at Module.load (node:internal/modules/cjs/loader:1074:32)
at Function.Module._load (node:internal/modules/cjs/loader:909:12)
at Module.require (node:internal/modules/cjs/loader:1098:19)
at require (node:internal/modules/cjs/helpers:108:18)
at Object. (D:\azarakhsh\node_modules\canvas\lib\canvas.js:9:18)
at Module._compile (node:internal/modules/cjs/loader:1196:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
at Module.load (node:internal/modules/cjs/loader:1074:32)
at Function.Module._load (node:internal/modules/cjs/loader:909:12)
at Module.require (node:internal/modules/cjs/loader:1098:19)
at require (node:internal/modules/cjs/helpers:108:18)
at Object. (D:\azarakhsh\node_modules\canvas\index.js:1:16)
at Module._compile (node:internal/modules/cjs/loader:1196:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
at Module.load (node:internal/modules/cjs/loader:1074:32)
at Function.Module._load (node:internal/modules/cjs/loader:909:12)
at Module.require (node:internal/modules/cjs/loader:1098:19)
at require (node:internal/modules/cjs/helpers:108:18)
at Object. (D:\azarakhsh\node_modules\filepix\lib\pdf2img.js:4:16)
at Module._compile (node:internal/modules/cjs/loader:1196:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
at Module.load (node:internal/modules/cjs/loader:1074:32)
at Function.Module._load (node:internal/modules/cjs/loader:909:12)
at Module.require (node:internal/modules/cjs/loader:1098:19)
at require (node:internal/modules/cjs/helpers:108:18)
at Object. (D:\azarakhsh\node_modules\filepix\index.js:4:17) {
code: 'ERR_DLOPEN_FAILED'
}`

**Comment by mskec** [comment] 2023-06-17 11:13
Hi @woxman,

Can you share a code snippet using `pdf2pic` that causes this error?

`canvas` is not a `pdf2pic` dependency, so I'm not sure if this is related to this library.

**Comment by woxman** [comment] 2023-06-17 12:57
> Hi @woxman,
> 
> Can you share a code snippet using `pdf2pic` that causes this error?
> 
> `canvas` is not a `pdf2pic` dependency, so I'm not sure if this is related to this library.
> 
> 
> 
> 

Const p2pic = Require('p2pic')

**Comment by mskec** [comment] 2023-06-17 13:51
I'm sorry, but I don't understand the issue and I don't believe it's caused by this library based on the input you gave here.

If you believe it's caused by pdf2pic, you are welcome to submit a minimal repository where I can reproduce the issue and investigate further.

In the mean time, I'm closing this issue.

**Closed by mskec** 2023-06-17 13:51 UTC
